# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cash',
            field=models.FloatField(default=0, verbose_name='dinheiro'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='pontos'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
