# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tie',
            field=models.BooleanField(default=False, verbose_name='empate'),
        ),
    ]
